import {
  Integration,
  KPIData,
  ProductRequest,
  RequestStatus,
  Order,
  OrderSource,
  OrderStatus,
  OrderType,
  Warehouse,
  WarehouseStatus,
  Product,
  StockStatus,
  User,
  UserRole,
  Shipment,
  ShipmentStatus,
  DeliveryPlatform,
  ActivityLog,
  TeamMember,
} from "./types";

// ==================== INTEGRATIONS ====================

export const initialIntegrations: Integration[] = [
  {
    id: "int-1",
    name: "Shopify Kenya",
    shortName: "SK",
    color: "bg-green-500",
    status: "Live",
    description: "Uncover Skincare Kenya",
    ordersToday: 24,
    region: "Kenya",
  },
  {
    id: "int-2",
    name: "Shopify Nigeria",
    shortName: "SN",
    color: "bg-green-600",
    status: "Live",
    description: "Uncover Skincare Nigeria",
    ordersToday: 18,
    region: "Nigeria",
  },
  {
    id: "int-3",
    name: "Odoo ERP",
    shortName: "OD",
    color: "bg-purple-600",
    status: "Connected",
    lastSync: "2 mins ago",
    region: "Both",
  },
  {
    id: "int-4",
    name: "QuickBooks",
    shortName: "QB",
    color: "bg-emerald-600",
    status: "Connected",
    lastSync: "5 mins ago",
    region: "Both",
  },
  {
    id: "int-5",
    name: "Leta AI",
    shortName: "LA",
    color: "bg-blue-600",
    status: "Connected",
    lastSync: "1 min ago",
    description: "Kenya Deliveries",
    region: "Kenya",
  },
  {
    id: "int-6",
    name: "Renda WMS",
    shortName: "RW",
    color: "bg-orange-500",
    status: "Connected",
    lastSync: "3 mins ago",
    description: "Nigeria Deliveries",
    region: "Nigeria",
  },
];

// ==================== KPIs ====================

export const initialKpis: KPIData[] = [
  {
    title: "Today's Orders",
    value: "42",
    subtext: "8 pending fulfillment",
    trend: "+18%",
    trendDirection: "up",
    icon: "orders",
  },
  {
    title: "Revenue (Today)",
    value: "KES 245,800",
    subtext: "vs KES 198,500 yesterday",
    trend: "+24%",
    trendDirection: "up",
    icon: "revenue",
  },
  {
    title: "Active Shipments",
    value: "5",
    subtext: "2 arriving this week",
    trend: "+2",
    trendDirection: "up",
    icon: "shipments",
  },
  {
    title: "Pending Requests",
    value: "3",
    subtext: "1 awaiting approval",
    trend: "-2",
    trendDirection: "down",
    icon: "requests",
  },
];

// ==================== USERS ====================

export const initialUsers: User[] = [
  {
    id: "user-1",
    name: "Alex Pierce",
    email: "alex.pierce@uncoverskincare.com",
    role: UserRole.SUPPLY_CHAIN_LEAD,
    department: "Supply Chain",
    avatar: "https://picsum.photos/seed/alex/100/100",
    phone: "+254 712 345 678",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      dashboardLayout: "detailed",
      timezone: "Africa/Nairobi",
      language: "en",
    },
    createdAt: "2024-01-15T08:00:00Z",
    lastLogin: "2026-02-08T09:30:00Z",
  },
  {
    id: "user-2",
    name: "Jane Mwangi",
    email: "jane.mwangi@uncoverskincare.com",
    role: UserRole.MANAGER,
    department: "Marketing",
    avatar: "https://picsum.photos/seed/jane/100/100",
    phone: "+254 723 456 789",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      dashboardLayout: "compact",
      timezone: "Africa/Nairobi",
      language: "en",
    },
    createdAt: "2024-02-01T08:00:00Z",
    lastLogin: "2026-02-07T16:45:00Z",
  },
  {
    id: "user-3",
    name: "Chidi Okonkwo",
    email: "chidi.okonkwo@uncoverskincare.com",
    role: UserRole.MANAGER,
    department: "Operations",
    avatar: "https://picsum.photos/seed/chidi/100/100",
    phone: "+234 801 234 5678",
    isActive: true,
    warehouseId: "wh-2",
    warehouseName: "Lagos Distribution Center",
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      dashboardLayout: "detailed",
      timezone: "Africa/Lagos",
      language: "en",
    },
    createdAt: "2024-01-20T08:00:00Z",
    lastLogin: "2026-02-08T08:15:00Z",
  },
  {
    id: "user-4",
    name: "Sarah Wambui",
    email: "sarah.wambui@uncoverskincare.com",
    role: UserRole.SUPPLY_CHAIN,
    department: "Supply Chain",
    avatar: "https://picsum.photos/seed/sarah/100/100",
    phone: "+254 734 567 890",
    managerId: "user-1",
    managerName: "Alex Pierce",
    warehouseId: "wh-1",
    warehouseName: "Nairobi Central Hub",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      dashboardLayout: "compact",
      timezone: "Africa/Nairobi",
      language: "en",
    },
    createdAt: "2024-03-10T08:00:00Z",
    lastLogin: "2026-02-08T07:00:00Z",
  },
  {
    id: "user-5",
    name: "Musa Keita",
    email: "musa.keita@uncoverskincare.com",
    role: UserRole.SUPPLY_CHAIN,
    department: "Supply Chain",
    avatar: "https://picsum.photos/seed/musa/100/100",
    phone: "+234 802 345 6789",
    managerId: "user-1",
    managerName: "Alex Pierce",
    warehouseId: "wh-2",
    warehouseName: "Lagos Distribution Center",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      dashboardLayout: "detailed",
      timezone: "Africa/Lagos",
      language: "en",
    },
    createdAt: "2024-03-15T08:00:00Z",
    lastLogin: "2026-02-08T09:00:00Z",
  },
  {
    id: "user-6",
    name: "Amina Hassan",
    email: "amina.hassan@uncoverskincare.com",
    role: UserRole.EMPLOYEE,
    department: "Marketing",
    avatar: "https://picsum.photos/seed/amina/100/100",
    phone: "+254 745 678 901",
    managerId: "user-2",
    managerName: "Jane Mwangi",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      dashboardLayout: "compact",
      timezone: "Africa/Nairobi",
      language: "en",
    },
    createdAt: "2024-04-01T08:00:00Z",
    lastLogin: "2026-02-07T14:30:00Z",
  },
  {
    id: "user-7",
    name: "David Onyango",
    email: "david.onyango@uncoverskincare.com",
    role: UserRole.ADMIN,
    department: "IT",
    avatar: "https://picsum.photos/seed/david/100/100",
    phone: "+254 756 789 012",
    isActive: true,
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      dashboardLayout: "detailed",
      timezone: "Africa/Nairobi",
      language: "en",
    },
    createdAt: "2024-01-01T08:00:00Z",
    lastLogin: "2026-02-08T10:00:00Z",
  },
];

// Helper to get managers
export const getManagers = (): TeamMember[] =>
  initialUsers
    .filter((u) => u.role === UserRole.MANAGER || u.role === UserRole.ADMIN)
    .map((u) => ({
      id: u.id,
      name: u.name,
      email: u.email,
      role: u.role,
      department: u.department,
    }));

// Helper to get supply chain team
export const getSupplyChainTeam = (): TeamMember[] =>
  initialUsers
    .filter(
      (u) =>
        u.role === UserRole.SUPPLY_CHAIN ||
        u.role === UserRole.SUPPLY_CHAIN_LEAD,
    )
    .map((u) => ({
      id: u.id,
      name: u.name,
      email: u.email,
      role: u.role,
      department: u.department,
    }));

// ==================== WAREHOUSES ====================

export const initialWarehouses: Warehouse[] = [
  {
    id: "wh-1",
    name: "Nairobi Central Hub",
    location: "Mombasa Rd, Industrial Area, Nairobi",
    region: "Kenya",
    capacity: 15000,
    occupancy: 72,
    manager: "John Kamau",
    managerId: "user-4",
    status: WarehouseStatus.ACTIVE,
    lastAudit: "Jan 28, 2026",
    deliveryPlatform: DeliveryPlatform.LETA_AI,
  },
  {
    id: "wh-2",
    name: "Lagos Distribution Center",
    location: "Apapa, Lagos",
    region: "Nigeria",
    capacity: 20000,
    occupancy: 65,
    manager: "Adaeze Nwosu",
    managerId: "user-5",
    status: WarehouseStatus.ACTIVE,
    lastAudit: "Jan 25, 2026",
    deliveryPlatform: DeliveryPlatform.RENDA_WMS,
  },
  {
    id: "wh-3",
    name: "Mombasa Port Facility",
    location: "Port Reitz, Mombasa",
    region: "Kenya",
    capacity: 8000,
    occupancy: 94,
    manager: "Hassan Ali",
    managerId: "user-4",
    status: WarehouseStatus.FULL,
    lastAudit: "Jan 20, 2026",
    deliveryPlatform: DeliveryPlatform.LETA_AI,
  },
  {
    id: "wh-4",
    name: "Abuja Storage Unit",
    location: "Gwagwalada, Abuja",
    region: "Nigeria",
    capacity: 5000,
    occupancy: 35,
    manager: "Ibrahim Yusuf",
    managerId: "user-5",
    status: WarehouseStatus.ACTIVE,
    lastAudit: "Feb 01, 2026",
    deliveryPlatform: DeliveryPlatform.RENDA_WMS,
  },
];

// ==================== PRODUCTS ====================

export const initialProducts: Product[] = [
  {
    id: "p1",
    name: "Aloe Invisible Sunscreen SPF 50",
    category: "Sun Protection",
    sku: "UNC-SUN-001",
    price: 19, // USD for calculations
    priceKES: 2450, // KES 2,450
    priceNGN: 14500, // NGN 14,500
    costPrice: 980,
    stock: 324,
    reservedStock: 15,
    availableStock: 309,
    reorderLevel: 100,
    status: StockStatus.IN_STOCK,
    image: "https://images.unsplash.com/photo-1617897903246-719242758050?w=200",
    description:
      "Ultra-lightweight sunscreen with no white cast, perfect for all skin tones.",
    warehouseId: "wh-1",
  },
  {
    id: "p2",
    name: "Vitamin C Brightening Serum",
    category: "Serums",
    sku: "UNC-SER-002",
    price: 29, // USD
    priceKES: 3800, // KES
    priceNGN: 22500, // NGN
    costPrice: 1520,
    stock: 189,
    reservedStock: 8,
    availableStock: 181,
    reorderLevel: 75,
    status: StockStatus.IN_STOCK,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=200",
    description: "15% Vitamin C serum for brighter, more even skin tone.",
    warehouseId: "wh-1",
  },
  {
    id: "p3",
    name: "Hydrating Gel Moisturizer",
    category: "Moisturizers",
    sku: "UNC-MOI-003",
    price: 23, // USD
    priceKES: 2999, // KES
    priceNGN: 18000, // NGN
    costPrice: 1200,
    stock: 45,
    reservedStock: 12,
    availableStock: 33,
    reorderLevel: 50,
    status: StockStatus.LOW_STOCK,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=200",
    description: "Lightweight gel moisturizer with hyaluronic acid.",
    warehouseId: "wh-1",
  },
  {
    id: "p4",
    name: "Gentle Foaming Cleanser",
    category: "Cleansers",
    sku: "UNC-CLN-004",
    price: 14, // USD
    priceKES: 1850, // KES
    priceNGN: 11000, // NGN
    costPrice: 740,
    stock: 0,
    reservedStock: 0,
    availableStock: 0,
    reorderLevel: 100,
    status: StockStatus.OUT_OF_STOCK,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200",
    description: "pH-balanced gentle cleanser for sensitive skin.",
    warehouseId: "wh-1",
  },
  {
    id: "p5",
    name: "Retinol Night Cream",
    category: "Anti-Aging",
    sku: "UNC-ANT-005",
    price: 35, // USD
    priceKES: 4500, // KES
    priceNGN: 27000, // NGN
    costPrice: 1800,
    stock: 156,
    reservedStock: 5,
    availableStock: 151,
    reorderLevel: 50,
    status: StockStatus.IN_STOCK,
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4b38b15?w=200",
    description: "Advanced retinol formula for reducing fine lines overnight.",
    warehouseId: "wh-2",
  },
  {
    id: "p6",
    name: "Niacinamide Pore Serum",
    category: "Serums",
    sku: "UNC-SER-006",
    price: 25, // USD
    priceKES: 3200, // KES
    priceNGN: 19500, // NGN
    costPrice: 1280,
    stock: 67,
    reservedStock: 3,
    availableStock: 64,
    reorderLevel: 40,
    status: StockStatus.IN_STOCK,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=200",
    description: "10% Niacinamide for refined pores and improved texture.",
    warehouseId: "wh-2",
  },
  {
    id: "p7",
    name: "Exfoliating Toner",
    category: "Toners",
    sku: "UNC-TON-007",
    price: 17, // USD
    priceKES: 2200, // KES
    priceNGN: 13500, // NGN
    costPrice: 880,
    stock: 23,
    reservedStock: 10,
    availableStock: 13,
    reorderLevel: 30,
    status: StockStatus.LOW_STOCK,
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=200",
    description: "AHA/BHA exfoliating toner for smooth, radiant skin.",
    warehouseId: "wh-2",
  },
];

// ==================== ORDERS ====================

export const initialOrders: Order[] = [
  {
    id: "ORD-2026-001",
    shopifyOrderId: "SH-KE-99501",
    source: OrderSource.SHOPIFY_KENYA,
    type: OrderType.B2C,
    customer: {
      name: "Grace Wanjiku",
      email: "grace.wanjiku@email.com",
      phone: "+254 712 345 678",
      address: "123 Westlands, Nairobi",
    },
    items: [
      {
        productId: "p1",
        productName: "Aloe Invisible Sunscreen SPF 50",
        sku: "UNC-SUN-001",
        quantity: 2,
        unitPrice: 2450,
        total: 4900,
      },
      {
        productId: "p2",
        productName: "Vitamin C Brightening Serum",
        sku: "UNC-SER-002",
        quantity: 1,
        unitPrice: 3800,
        total: 3800,
      },
    ],
    subtotal: 8700,
    shipping: 350,
    total: 9050,
    currency: "KES",
    status: OrderStatus.PROCESSING,
    sync: {
      odooSO: "success",
      odooInvoice: "success",
      qbInvoice: "success",
      delivery: "pending",
      deliveryPlatform: DeliveryPlatform.LETA_AI,
    },
    createdAt: "2026-02-08T08:30:00Z",
    updatedAt: "2026-02-08T08:35:00Z",
  },
  {
    id: "ORD-2026-002",
    shopifyOrderId: "SH-NG-88201",
    source: OrderSource.SHOPIFY_NIGERIA,
    type: OrderType.B2C,
    customer: {
      name: "Chioma Eze",
      email: "chioma.eze@email.com",
      phone: "+234 801 234 5678",
      address: "45 Victoria Island, Lagos",
    },
    items: [
      {
        productId: "p5",
        productName: "Retinol Night Cream",
        sku: "UNC-ANT-005",
        quantity: 1,
        unitPrice: 4500,
        total: 4500,
      },
    ],
    subtotal: 4500,
    shipping: 500,
    total: 5000,
    currency: "NGN",
    status: OrderStatus.IN_TRANSIT,
    sync: {
      odooSO: "success",
      odooInvoice: "success",
      qbInvoice: "success",
      delivery: "success",
      deliveryPlatform: DeliveryPlatform.RENDA_WMS,
    },
    trackingNumber: "RW-NG-2026-45678",
    createdAt: "2026-02-07T14:20:00Z",
    updatedAt: "2026-02-08T06:00:00Z",
    fulfilledAt: "2026-02-07T16:30:00Z",
  },
  {
    id: "ORD-2026-003",
    shopifyOrderId: "SH-KE-99502",
    source: OrderSource.SHOPIFY_KENYA,
    type: OrderType.B2C,
    customer: {
      name: "Peter Odhiambo",
      email: "peter.o@email.com",
      phone: "+254 723 456 789",
      address: "78 Kilimani, Nairobi",
    },
    items: [
      {
        productId: "p3",
        productName: "Hydrating Gel Moisturizer",
        sku: "UNC-MOI-003",
        quantity: 2,
        unitPrice: 2999,
        total: 5998,
      },
      {
        productId: "p6",
        productName: "Niacinamide Pore Serum",
        sku: "UNC-SER-006",
        quantity: 1,
        unitPrice: 3200,
        total: 3200,
      },
    ],
    subtotal: 9198,
    shipping: 350,
    total: 9548,
    currency: "KES",
    status: OrderStatus.DELIVERED,
    sync: {
      odooSO: "success",
      odooInvoice: "success",
      qbInvoice: "success",
      delivery: "success",
      deliveryPlatform: DeliveryPlatform.LETA_AI,
    },
    trackingNumber: "LA-KE-2026-12345",
    createdAt: "2026-02-05T10:15:00Z",
    updatedAt: "2026-02-07T11:00:00Z",
    fulfilledAt: "2026-02-05T14:00:00Z",
    deliveredAt: "2026-02-07T11:00:00Z",
  },
  {
    id: "ORD-2026-004",
    odooInvoiceId: "INV-2026-0045",
    source: OrderSource.B2B_ODOO,
    type: OrderType.B2B,
    customer: {
      name: "Beauty Haven Stores",
      email: "orders@beautyhaven.co.ke",
      phone: "+254 700 111 222",
      address: "Sarit Centre, Westlands, Nairobi",
    },
    items: [
      {
        productId: "p1",
        productName: "Aloe Invisible Sunscreen SPF 50",
        sku: "UNC-SUN-001",
        quantity: 50,
        unitPrice: 1960,
        total: 98000,
      },
      {
        productId: "p2",
        productName: "Vitamin C Brightening Serum",
        sku: "UNC-SER-002",
        quantity: 30,
        unitPrice: 3040,
        total: 91200,
      },
    ],
    subtotal: 189200,
    shipping: 0,
    total: 189200,
    currency: "KES",
    status: OrderStatus.PROCESSING,
    sync: {
      odooSO: "success",
      odooInvoice: "success",
      qbInvoice: "pending",
      delivery: "not_required",
      deliveryPlatform: DeliveryPlatform.NONE,
    },
    createdAt: "2026-02-06T09:00:00Z",
    updatedAt: "2026-02-06T09:15:00Z",
  },
  {
    id: "ORD-2026-005",
    shopifyOrderId: "SH-NG-88202",
    source: OrderSource.SHOPIFY_NIGERIA,
    type: OrderType.B2C,
    customer: {
      name: "Adaora Nnamdi",
      email: "adaora.n@email.com",
      phone: "+234 802 345 6789",
      address: "12 Lekki Phase 1, Lagos",
    },
    items: [
      {
        productId: "p7",
        productName: "Exfoliating Toner",
        sku: "UNC-TON-007",
        quantity: 1,
        unitPrice: 2200,
        total: 2200,
      },
    ],
    subtotal: 2200,
    shipping: 450,
    total: 2650,
    currency: "NGN",
    status: OrderStatus.PENDING,
    sync: {
      odooSO: "pending",
      odooInvoice: "pending",
      qbInvoice: "pending",
      delivery: "pending",
      deliveryPlatform: DeliveryPlatform.RENDA_WMS,
    },
    createdAt: "2026-02-08T10:45:00Z",
    updatedAt: "2026-02-08T10:45:00Z",
  },
];

// ==================== PRODUCT REQUESTS ====================

export const initialRequests: ProductRequest[] = [
  {
    id: "REQ-2026-001",
    productId: "p1",
    productName: "Aloe Invisible Sunscreen SPF 50",
    quantity: 20,
    reason: "Influencer gifting campaign for Valentine's Day promotion",
    requesterId: "user-6",
    requesterName: "Amina Hassan",
    requesterEmail: "amina.hassan@uncoverskincare.com",
    approverId: "user-2",
    approverName: "Jane Mwangi",
    approverEmail: "jane.mwangi@uncoverskincare.com",
    status: RequestStatus.PENDING_APPROVAL,
    createdAt: "2026-02-07T14:00:00Z",
  },
  {
    id: "REQ-2026-002",
    productId: "p2",
    productName: "Vitamin C Brightening Serum",
    quantity: 10,
    reason: "Product samples for upcoming beauty expo",
    requesterId: "user-6",
    requesterName: "Amina Hassan",
    requesterEmail: "amina.hassan@uncoverskincare.com",
    approverId: "user-2",
    approverName: "Jane Mwangi",
    approverEmail: "jane.mwangi@uncoverskincare.com",
    status: RequestStatus.APPROVED,
    assignedTo: "user-4",
    assignedToName: "Sarah Wambui",
    createdAt: "2026-02-05T10:00:00Z",
    approvedAt: "2026-02-05T14:30:00Z",
  },
  {
    id: "REQ-2026-003",
    productId: "p5",
    productName: "Retinol Night Cream",
    quantity: 5,
    reason: "PR kit for media reviews",
    requesterId: "user-6",
    requesterName: "Amina Hassan",
    requesterEmail: "amina.hassan@uncoverskincare.com",
    approverId: "user-2",
    approverName: "Jane Mwangi",
    approverEmail: "jane.mwangi@uncoverskincare.com",
    status: RequestStatus.READY_FOR_COLLECTION,
    assignedTo: "user-4",
    assignedToName: "Sarah Wambui",
    collectionPoint: "Nairobi Central Hub - Reception",
    createdAt: "2026-02-01T09:00:00Z",
    approvedAt: "2026-02-01T11:00:00Z",
    readyAt: "2026-02-02T10:00:00Z",
  },
];

// ==================== SHIPMENTS ====================

export const initialShipments: Shipment[] = [
  {
    id: "SHP-2026-001",
    reference: "PO-2026-0089",
    supplier: "Cosmetics Manufacturing Co. Ltd",
    origin: "Guangzhou, China",
    destinationWarehouseId: "wh-1",
    destinationWarehouse: "Nairobi Central Hub",
    items: [
      {
        productId: "p4",
        productName: "Gentle Foaming Cleanser",
        sku: "UNC-CLN-004",
        quantity: 500,
        unitCost: 740,
        totalCost: 370000,
      },
      {
        productId: "p3",
        productName: "Hydrating Gel Moisturizer",
        sku: "UNC-MOI-003",
        quantity: 300,
        unitCost: 1200,
        totalCost: 360000,
      },
    ],
    totalUnits: 800,
    totalValue: 730000,
    currency: "KES",
    status: ShipmentStatus.IN_TRANSIT,
    carrier: "Maersk Line",
    containerNumber: "MSKU-7654321",
    trackingNumber: "MAEU-2026-56789",
    estimatedArrival: "2026-02-15",
    createdBy: "Alex Pierce",
    createdById: "user-1",
    createdAt: "2026-01-20T09:00:00Z",
    notes:
      "Contains restocking items for Q1. Handle with care - temperature sensitive products.",
  },
  {
    id: "SHP-2026-002",
    reference: "PO-2026-0092",
    supplier: "Skincare Essentials Ltd",
    origin: "Seoul, South Korea",
    destinationWarehouseId: "wh-2",
    destinationWarehouse: "Lagos Distribution Center",
    items: [
      {
        productId: "p7",
        productName: "Exfoliating Toner",
        sku: "UNC-TON-007",
        quantity: 400,
        unitCost: 880,
        totalCost: 352000,
      },
    ],
    totalUnits: 400,
    totalValue: 352000,
    currency: "KES",
    status: ShipmentStatus.CUSTOMS_CLEARANCE,
    carrier: "DHL Global Forwarding",
    trackingNumber: "DHL-2026-34567",
    estimatedArrival: "2026-02-12",
    createdBy: "Alex Pierce",
    createdById: "user-1",
    createdAt: "2026-01-25T11:00:00Z",
    notes: "Awaiting customs clearance at Apapa port.",
  },
  {
    id: "SHP-2026-003",
    reference: "PO-2026-0095",
    supplier: "Natural Ingredients Co.",
    origin: "Mumbai, India",
    destinationWarehouseId: "wh-1",
    destinationWarehouse: "Nairobi Central Hub",
    items: [
      {
        productId: "p1",
        productName: "Aloe Invisible Sunscreen SPF 50",
        sku: "UNC-SUN-001",
        quantity: 1000,
        unitCost: 980,
        totalCost: 980000,
      },
    ],
    totalUnits: 1000,
    totalValue: 980000,
    currency: "KES",
    status: ShipmentStatus.CREATED,
    carrier: "MSC",
    estimatedArrival: "2026-03-01",
    createdBy: "Alex Pierce",
    createdById: "user-1",
    createdAt: "2026-02-05T14:00:00Z",
    notes:
      "Large order for Q2 inventory buildup. Sunscreen restock for peak season.",
  },
  {
    id: "SHP-2026-004",
    reference: "PO-2025-0156",
    supplier: "Cosmetics Manufacturing Co. Ltd",
    origin: "Guangzhou, China",
    destinationWarehouseId: "wh-2",
    destinationWarehouse: "Lagos Distribution Center",
    items: [
      {
        productId: "p5",
        productName: "Retinol Night Cream",
        sku: "UNC-ANT-005",
        quantity: 200,
        unitCost: 1800,
        totalCost: 360000,
      },
      {
        productId: "p6",
        productName: "Niacinamide Pore Serum",
        sku: "UNC-SER-006",
        quantity: 150,
        unitCost: 1280,
        totalCost: 192000,
      },
    ],
    totalUnits: 350,
    totalValue: 552000,
    currency: "KES",
    status: ShipmentStatus.RECEIVED,
    carrier: "Evergreen Marine",
    containerNumber: "EGHU-1234567",
    trackingNumber: "EVER-2025-98765",
    estimatedArrival: "2026-01-28",
    actualArrival: "2026-01-29",
    createdBy: "Alex Pierce",
    createdById: "user-1",
    createdAt: "2025-12-15T10:00:00Z",
    receivedBy: "Musa Keita",
    receivedAt: "2026-01-29T14:30:00Z",
    notes: "Received in good condition. All items verified.",
  },
];

// ==================== ACTIVITY LOG ====================

export const initialActivityLog: ActivityLog[] = [
  {
    id: "act-1",
    type: "order",
    message: "New order received from Shopify Kenya",
    details: "Order #ORD-2026-001 - Grace Wanjiku - KES 9,050",
    timestamp: "2026-02-08T08:30:00Z",
    userName: "System",
  },
  {
    id: "act-2",
    type: "sync",
    message: "Order synced to Odoo successfully",
    details: "Sales Order SO-2026-0089 created",
    timestamp: "2026-02-08T08:31:00Z",
    userName: "System",
  },
  {
    id: "act-3",
    type: "request",
    message: "New product request submitted",
    details: "REQ-2026-001 - 20x Aloe Invisible Sunscreen",
    timestamp: "2026-02-07T14:00:00Z",
    userId: "user-6",
    userName: "Amina Hassan",
  },
  {
    id: "act-4",
    type: "shipment",
    message: "Shipment status updated",
    details: "SHP-2026-002 now in Customs Clearance",
    timestamp: "2026-02-07T10:00:00Z",
    userName: "System",
  },
  {
    id: "act-5",
    type: "order",
    message: "Order delivered successfully",
    details: "Order #ORD-2026-003 - Peter Odhiambo",
    timestamp: "2026-02-07T11:00:00Z",
    userName: "Leta AI",
  },
];
